






const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
		   ,{
			   "child":[
				   {
					   "buttons":[
						   "查看",
						   "新增",
						   "修改",
						   "删除"
					   ],
					   "menu":"住户管理",
					   "menuJump":"列表",
					   "tableName":"zhuhu"
				   }
			   ],
			   "menu":"住户管理"
		   }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"隔离监控管理",
                        "menuJump":"列表",
                        "tableName":"geli"
                    }
                ],
                "menu":"隔离监控管理"
            }
            
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"疫情上报管理",
                        "menuJump":"列表",
                        "tableName":"shangbao"
                    }
                ],
                "menu":"疫情上报管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"社区人员出入管理",
                        "menuJump":"列表",
                        "tableName":"shequchuru"
                    }
                ],
                "menu":"社区人员出入管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"疫情通知管理",
			            "menuJump":"列表",
			            "tableName":"gonggao"
			        }
			    ],
			    "menu":"疫情通知管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"疫情通知类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryGonggao"
			        }
			    ],
			    "menu":"疫情通知类型管理"
			}
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"隔离监控管理",
	                    "menuJump":"列表",
	                    "tableName":"geli"
	                }
	            ],
	            "menu":"隔离监控管理"
	        }
	        
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"疫情上报管理",
	                    "menuJump":"列表",
	                    "tableName":"shangbao"
	                }
	            ],
	            "menu":"疫情上报管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"社区人员出入管理",
	                    "menuJump":"列表",
	                    "tableName":"shequchuru"
	                }
	            ],
	            "menu":"社区人员出入管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"疫情通知管理",
			            "menuJump":"列表",
			            "tableName":"gonggao"
			        }
			    ],
			    "menu":"疫情通知管理"
			}
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"住户",
	    "tableName":"zhuhu"
	}
]
    }
}
export default menu;
